import { ArrowRight, BarChart3, BookOpen, Bot, Globe2, Send, ShieldCheck } from 'lucide-react'
import type { Navigate } from '../../types/navigation'
import './HomePage.css'

export function HomePage({ navigate }: { navigate: Navigate }) {
  return <main className="home"><section className="hero">
    <div className="hero-copy"><span className="eyebrow">Ciudadanía digital para todas las personas</span><h1>Comprueba antes<br />de <em>compartir.</em></h1><p>Verifica información, comprende la evidencia y fortalece tu criterio digital en una plataforma clara, pública y educativa.</p><div className="actions"><button className="primary" onClick={() => navigate('chat')}>Verificar una noticia <ArrowRight size={16} /></button><button className="secondary" onClick={() => navigate('learn')}>Explorar recursos</button></div><small className="trust"><ShieldCheck size={16} />Evidencia visible. Fuentes consultables. Decisiones informadas.</small></div>
    <div className="modules"><button className="window bot-window" onClick={() => navigate('chat')}><div className="window-bar"><span /><span /><span /><b>VERIFIBOT</b></div><div className="bot-body"><i className="bot-icon"><Bot size={30} /></i><small>● EN LÍNEA</small><h2>Hola, soy VERIFIBOT</h2><p>¿Qué información te gustaría verificar?</p><div className="fake-input">Pega una noticia o escribe una afirmación… <Send size={15} /></div></div><footer>Abrir VERIFIBOT <ArrowRight size={15} /></footer></button><div className="mini-stack"><button className="window mini-window" onClick={() => navigate('learn')}><i><BookOpen size={20} /></i><small>APRENDER</small><h3>Detecta la desinformación</h3><p>Lecciones breves y ejercicios prácticos.</p></button><button className="window mini-window" onClick={() => navigate('dashboard')}><i className="coral"><BarChart3 size={20} /></i><small>MÉTRICAS</small><h3>Tu impacto digital</h3><p><b>18</b> verificaciones esta semana</p></button></div></div>
  </section><section className="value-strip">{[[Globe2, 'Información abierta', 'Consulta las fuentes detrás de cada respuesta.'], [BookOpen, 'Aprendizaje práctico', 'Aprende mientras verificas contenido real.'], [ShieldCheck, 'Criterio, no dependencia', 'Te ayudamos a tomar tus propias decisiones.']].map(([Icon, title, text]) => { const ItemIcon = Icon as typeof Globe2; return <div key={title as string}><ItemIcon size={20} /><span><b>{title as string}</b>{text as string}</span></div> })}</section></main>
}
